version: '3.8'

services:
  mongo:
    image: mongo:5.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo-db:/data/db
    networks:
      - app-network

  boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
    depends_on:
      - mongo
    networks:
      - app-network
    ports:
      - "8080:8080"

volumes:
  mongo-db:

networks:
  app-network:
